---
abstract: 'XMPP inbound service for Tatsumaki'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tatsumaki-Service-XMPP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent::XMPP: 0
  Filter::Util::Call: 0
  HTTP::Message::PSGI: 0
  LWP: 0
  Tatsumaki: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Tatsumaki-Service-XMPP.git
version: 0.01
